name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  ci-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make all
    - name: test
      run: |
        make tests
        ./build/debug/test
  ci-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make all
    - name: test
      run: |
        make tests
        ./build/debug/test
